# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://mnjm.github.io/kayal/docs/configuration/#theme-parameters

# Site logo, this will be added before Site Title in the header
# logo = "/imgs/logo.png"
# Site description
# description = "A Hugo Theme"
# Copyright owner name
copyright = ""

enableCodeCopy = true
showThemeSwitcher = true
defaultTheme = "auto" # Valid Options: light, dark, auto
highlightCurrentMenu = true
mainSections = ["posts"]
removeAttribution = false
showHeadingAnchors = true

# [verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""

[homepage]
headline = "👋 Welcome to my site"
# profile image
image = "imgs/profile.svg"
# image position
where = "right" # right, left, top
showRecent = true
showRecentLabel = "Featured"
showRecentItems = 4
showReadMore = true
showMore = true
showMoreDest = "/posts"

[list]
groupByYear = false
showDate = true

[article]
hidden = false
externalURL = false
showDate = true
showModDate = true
showReadingTime = true
showTags = true
showPagination = true
invertPagination = true
showToC = true
openToC = false
showComments = false

[taxonomy]
showCount = true
cardView = true

[term]
groupByYear = false
showDate = true

[[social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mnjm/kayal"

[[social]]
name = "Demo"
icon = "wand-magic-sparkles"
url = "https://mnjm.github.io/kayal"
