baseURL = 'https://mnjm.github.io/kayal'
languageCode = 'en-us'
title = 'Kayal'
theme = "kayal"
paginate = 10
enableEmoji = true

# [services]
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'
