# Add a training '/' to local project urls.
# For ex: /posts/
# NOT: /posts

[[main]]
name = "Docs"
url = "/docs/"
weight = 1

[[main]]
name = "Examples"
url = "/examples/"
weight = 2

[[main]]
name = "Shortcodes"
url = "/shortcodes/"
weight = 3

[[main]]
pre = "github"
name = ""
url = "https://github.com/mnjm/kayal"
weight = 4
