logo = "/imgs/logo.png"
copyright = "Manjunath Mohan"
enableCodeCopy = true
removeAttribution = false
showThemeSwitcher = true
defaultTheme = "auto" # light, dark, auto
highlightCurrentMenu = true
mainSections = ["docs"]

[homepage]
headline = "👋 Welcome"
image = "imgs/profile.png"
where = "top" # right, left, top
showRecent = true
showRecentLabel = "Featured"
showRecentItems = 4
showMore = true
showMoreDest = "/docs"

[list]
groupByYear = false
showDate = true

[article]
hidden = false
showDate = true
showModDate = true
showReadingTime = true
showPagination = true
invertPagination = true
showToC = true
openToC = false

[taxonomy]
showCount = true
cardView = true

[term]
groupByYear = false
showDate = true

[[social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mnjm/kayal"

[[social]]
name = "Demo"
icon = "link"
url = "https://mnjm.github.io/kayal"
